import { Feather } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { ChannelRow } from '@/components/ChannelRow';
import { useIptv } from '@/context/iptv-context';
import { useColors } from '@/hooks/useColors';
export default function FavoritesScreen() { const colors = useColors(); const insets = useSafeAreaInsets(); const router = useRouter(); const { channels, favorites, isFavorite, toggleFavorite } = useIptv(); const saved = channels.filter((channel) => favorites.includes(channel.id)); return <View style={[styles.root, { backgroundColor: colors.background }]}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={[styles.content, { paddingTop: insets.top + 22, paddingBottom: insets.bottom + 104 }]}><View style={styles.heading}><View><Text style={[styles.kicker, { color: colors.primary }]}>YOUR LIBRARY</Text><Text style={[styles.title, { color: colors.foreground }]}>Favorites</Text></View><View style={[styles.count, { backgroundColor: colors.secondary }]}><Text style={[styles.countText, { color: colors.secondaryForeground }]}>{saved.length}</Text></View></View><Text style={[styles.subtitle, { color: colors.mutedForeground }]}>Your saved channels, ready when you are.</Text>{saved.length ? saved.map((channel) => <ChannelRow key={channel.id} channel={channel} favorite={isFavorite(channel.id)} onPress={() => router.push({ pathname: '/channel/[id]', params: { id: channel.id } })} onToggleFavorite={() => toggleFavorite(channel.id)} />) : <View style={[styles.empty, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.emptyIcon, { backgroundColor: colors.secondary }]}><Feather name="heart" size={24} color={colors.primary} /></View><Text style={[styles.emptyTitle, { color: colors.foreground }]}>Nothing saved yet</Text><Text style={[styles.emptyText, { color: colors.mutedForeground }]}>Tap the heart on any channel to keep it close.</Text></View>}</ScrollView></View>; }
const styles = StyleSheet.create({ root: { flex: 1 }, content: { paddingHorizontal: 18 }, heading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end' }, kicker: { fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 1.6, marginBottom: 7 }, title: { fontFamily: 'Inter_700Bold', fontSize: 32, letterSpacing: -1.2 }, count: { minWidth: 34, height: 34, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginBottom: 4 }, countText: { fontFamily: 'Inter_700Bold', fontSize: 14 }, subtitle: { fontFamily: 'Inter_400Regular', fontSize: 13, marginTop: 8, marginBottom: 24 }, empty: { borderWidth: 1, borderRadius: 20, minHeight: 230, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 35, gap: 9 }, emptyIcon: { width: 56, height: 56, borderRadius: 19, alignItems: 'center', justifyContent: 'center', marginBottom: 4 }, emptyTitle: { fontFamily: 'Inter_700Bold', fontSize: 18 }, emptyText: { fontFamily: 'Inter_400Regular', fontSize: 13, lineHeight: 19, textAlign: 'center' } });
